//player check position [varX] [varY] [varZ] - sets variable x/y/z to the player's current position.
player check position global.playerX global.playerY global.playerZ

global.playerNormX*=0
global.playerNormY*=0
global.playerNormZ*=0

global.playerNormX+="$global.playerX"
global.playerNormX-=$global.lastX
global.playerNormX*=$global.playerNormX//Square it

global.playerNormY+="$global.playerY"
global.playerNormY-=$global.lastY
global.playerNormY*=$global.playerNormY//Square it
//Fix me cannot use procedures in the loop scripts have to get the Babylonian square root estimation by hand below can't use loops
global.playerNormZ+="$global.playerZ"
global.playerNormZ-=$global.lastZ
global.playerNormZ*=$global.playerNormZ//Square it

//get ||v|| = sqrt(x^2 + y^2 + z^2)
v*=0
v+=$global.playerNormX
v+=$global.playerNormY
v+=$global.playerNormZ
//status $v 1


//1 get guess
avg = $global.playerX
avg+=$global.playerY
avg+=$global.playerZ

avg/=3
//status $avg 1
status "here" 1

player check position global.lastX global.lastY global.lastZ
//status "global.playerNormX $global.playerNormX , $global.playerX $global.playerNormY , $global.playerY $global.playerNormZ , $global.playerZ" 1

